name: webview_flutter_plus
description: An extension of webview_flutter to load local HTML,CSS and Javascript from Assets or Strings and much more.

version: 0.4.20

homepage: https://github.com/Shahxad-Akram/webview_flutter_plus

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.14.1
  webview_flutter_wkwebview: any
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
